import { useState, Fragment } from "react"; // ✅ Import Fragment
import { Button } from "@chakra-ui/react";
import { FaBook } from "react-icons/fa";
import { pdf, Document, Page, Text, View } from "@react-pdf/renderer";
import { CourseService } from "~/services/courseService";
import { LessonService } from "~/services/lessonService";
import { toaster } from "~/components/ui/toaster";
import { styles } from "./pdfStyles";
import { renderLessonBlocks } from "./pdfUtils";
import { useConfigStore } from "~/store/configStore";

// ✅ HELPER: Clean redundant titles
const cleanTitle = (prefix: string, title: string) => {
  const normalizedTitle = title.trim();
  const normalizedPrefix = prefix.trim();

  if (
    normalizedTitle.toLowerCase().startsWith(normalizedPrefix.toLowerCase())
  ) {
    return normalizedTitle;
  }
  return `${normalizedPrefix}: ${normalizedTitle}`;
};

// --- THE COURSE DOCUMENT STRUCTURE ---
const CourseDocument = ({ course }: any) => (
  <Document>
    {/* 1. MASTER COVER PAGE */}
    <Page size="A4" style={styles.coverPage}>
      <Text
        style={{
          fontSize: 12,
          letterSpacing: 4,
          marginBottom: 20,
          color: "#a0aec0",
        }}
      >
        COMPLETE COURSE MATERIAL
      </Text>
      <Text style={styles.courseTitle}>{course.title}</Text>
      <Text style={styles.moduleDesc}>
        {course.description || "Comprehensive Study Guide"}
      </Text>

      <View style={styles.courseStats}>
        <Text>
          {course.modules?.length || 0} Modules •{" "}
          {course.modules?.reduce(
            (acc: number, m: any) => acc + (m.lessons?.length || 0),
            0,
          )}{" "}
          Lessons
        </Text>
      </View>

      <Text style={styles.footer}>Generated by CourseForge AI</Text>
    </Page>

    {/* 2. MASTER TABLE OF CONTENTS */}
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Table of Contents</Text>
      {course.modules?.map((module: any, mIndex: number) => {
        const moduleLabel = cleanTitle(`Module ${mIndex + 1}`, module.title);

        return (
          <View key={mIndex} wrap={false} style={styles.tocModuleContainer}>
            <Text style={styles.tocModuleTitle}>{moduleLabel}</Text>
            {module.lessons?.map((lesson: any, lIndex: number) => {
              const lessonLabel = cleanTitle(
                `${mIndex + 1}.${lIndex + 1}`,
                lesson.title || "Lesson",
              );
              return (
                <Text key={lIndex} style={styles.tocLessonItem}>
                  {lessonLabel}
                </Text>
              );
            })}
          </View>
        );
      })}
    </Page>

    {/* 3. CONTENT LOOP (Modules -> Lessons) */}
    {course.modules?.map((module: any, mIndex: number) => (
      // ✅ FIX: Use Fragment instead of View to wrap multiple pages
      <Fragment key={module._id || mIndex}>
        {/* A. Module Separator Page */}
        <Page size="A4" style={styles.moduleCoverPage}>
          <Text
            style={{
              fontSize: 14,
              color: "#4299e1",
              marginBottom: 10,
              textTransform: "uppercase",
            }}
          >
            Module {mIndex + 1}
          </Text>
          <Text style={styles.moduleCoverTitle}>{module.title}</Text>
          {module.description && (
            <Text
              style={{ marginTop: 20, color: "#4a5568", textAlign: "center" }}
            >
              {module.description}
            </Text>
          )}
        </Page>

        {/* B. Lessons in this Module */}
        {module.lessons?.map((lesson: any, lIndex: number) => {
          const lessonHeader = cleanTitle(
            `${mIndex + 1}.${lIndex + 1}`,
            lesson.title,
          );

          return (
            <Page key={lesson.id || lIndex} size="A4" style={styles.page}>
              {/* Header with Hierarchy Context */}
              <View style={{ marginBottom: 30 }}>
                <Text style={styles.subHeader}>
                  {cleanTitle(`Module ${mIndex + 1}`, module.title)}
                </Text>
                <Text style={styles.lessonTitle}>{lessonHeader}</Text>
              </View>

              {/* Render Content */}
              {renderLessonBlocks(lesson.content || [])}

              {/* Footer */}
              <Text style={styles.footer} fixed>
                {course.title} • Module {mIndex + 1} • Lesson {lIndex + 1}
              </Text>
            </Page>
          );
        })}
      </Fragment>
    ))}
  </Document>
);

interface CoursePDFExporterProps {
  course: any;
}

export const CoursePDFButton = ({ course }: CoursePDFExporterProps) => {
  const [loading, setLoading] = useState(false);
  const [loadingText, setLoadingText] = useState("Building...");
  const getCost = useConfigStore((state) => state.getCost);
  const cost = getCost("exportCoursePdf");

  const handleDownload = async () => {
    setLoading(true);
    setLoadingText("Initializing...");
    try {
      let fullCourse = { ...course };

      // --- 1. RESOLVE COURSE STRUCTURE ---
      const hasUnpopulatedModules =
        !fullCourse.modules ||
        (fullCourse.modules.length > 0 &&
          typeof fullCourse.modules[0] === "string");

      if (hasUnpopulatedModules) {
        setLoadingText("Fetching Course Outline...");
        fullCourse = await CourseService.getCourseById(
          fullCourse._id || fullCourse.id,
        );
      }

      if (!fullCourse.modules || fullCourse.modules.length === 0) {
        throw new Error("Course content is empty.");
      }

      // --- 2. SEQUENTIAL DEEP FETCHING (One by One) ---
      const totalModules = fullCourse.modules.length;
      const fetchedModules = [];

      for (let i = 0; i < totalModules; i++) {
        let module = fullCourse.modules[i];

        if (typeof module === "string") {
          module = { _id: module, title: "Unknown Module", lessons: [] };
        }

        const lessons = module.lessons || [];

        const needsRefetch = lessons.some(
          (l: any) =>
            typeof l === "string" ||
            !l.content ||
            (Array.isArray(l.content) && l.content.length === 0),
        );

        if (needsRefetch) {
          setLoadingText(`Fetching Module ${i + 1}/${totalModules}...`);

          const fetchedLessons = [];
          for (const lesson of lessons) {
            const lessonId =
              typeof lesson === "string" ? lesson : lesson._id || lesson.id;
            try {
              const fullLesson = await LessonService.getLessonById(lessonId);
              fetchedLessons.push(fullLesson);
            } catch (err) {
              console.warn(`Failed to fetch lesson ${lessonId}`, err);
              fetchedLessons.push(lesson);
            }
          }
          module = { ...module, lessons: fetchedLessons };
        }
        fetchedModules.push(module);
      }

      const finalCourse = { ...fullCourse, modules: fetchedModules };

      // --- 3. COMPILING ---
      setLoadingText("Compiling PDF...");
      await CourseService.deductCoursePDFCredits(
        finalCourse.id || finalCourse._id,
      );

      // --- 4. GENERATE & DOWNLOAD ---
      const doc = <CourseDocument course={finalCourse} />;
      const blob = await pdf(doc).toBlob();

      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      const safeTitle = (finalCourse.title || "Course").replace(/\s+/g, "_");
      link.download = `${safeTitle}_Complete_Course.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toaster.create({ title: "Download Complete", type: "success" });
    } catch (error: any) {
      console.error("Course Export Failed:", error);
      toaster.create({
        title: "Export Failed",
        description: error.message,
        type: "error",
      });
    } finally {
      setLoading(false);
      setLoadingText("Building...");
    }
  };

  return (
    <Button
      size="sm"
      colorPalette="orange"
      variant="solid"
      onClick={handleDownload}
      loading={loading}
      loadingText={loadingText}
      px={6}
    >
      <FaBook /> Download Full Course (-${cost})
    </Button>
  );
};
