// src/components/pdf/LessonPDFButton.tsx
import { useState } from "react";
import { Button } from "@chakra-ui/react";
import { FaDownload } from "react-icons/fa";
import { pdf, Document, Page, Text, View, Link, Image } from "@react-pdf/renderer";
import { CourseService } from "~/services/courseService";
import { toaster } from "~/components/ui/toaster";
import { styles } from "./pdfStyles";
import { renderLessonBlocks } from "./pdfUtils";
import { useConfigStore } from "~/store/configStore";

// Internal Document Component
const LessonDocument = ({ lesson }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.subHeader}>Single Lesson Export</Text>
        <Text style={styles.title}>{lesson.title}</Text>
      </View>
      
      {/* Objectives */}
      {lesson.objectives?.length > 0 && (
          <View style={{ marginBottom: 20, padding: 15, backgroundColor: "#ebf8ff", borderLeftWidth: 4, borderLeftColor: "#3182ce" }}>
            <Text style={{ fontFamily: "RobotoBold", marginBottom: 5, color: "#2c5282" }}>KEY TAKEAWAYS</Text>
            {lesson.objectives.map((obj: string, i: number) => (
              <Text key={i} style={{ fontSize: 11, marginBottom: 2 }}>• {obj}</Text>
            ))}
          </View>
      )}

      {renderLessonBlocks(lesson.content)}
      
      <Text style={styles.footer} fixed>Generated by CourseForge AI</Text>
    </Page>
  </Document>
);

export const LessonPDFButton = ({ lesson }: { lesson: any }) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const getCost = useConfigStore((state) => state.getCost);
  const COST = getCost("exportPdf") || 5;

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      if (!lesson._id && !lesson.id) throw new Error("Invalid Lesson ID");

      // 1. Deduct Credits
      await CourseService.deductPDFCredits(lesson._id || lesson.id);
      toaster.create({ description: "Generating PDF...", type: "success" });

      // 2. Generate
      const blob = await pdf(<LessonDocument lesson={lesson} />).toBlob();
      
      // 3. Save
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${lesson.title.replace(/\s+/g, "_")}.pdf`;
      link.click();
      URL.revokeObjectURL(url);

    } catch (error: any) {
      toaster.create({ title: "Failed", description: error.message, type: "error" });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <Button
      size="sm"
      variant="outline"
      colorPalette="blue"
      onClick={handleDownload}
      loading={isDownloading}
      loadingText="Exporting..."
    >
      <FaDownload /> Lesson PDF (-{COST})
    </Button>
  );
};