import { useState } from "react";
import { Button } from "@chakra-ui/react";
import { FaFilePdf } from "react-icons/fa";
import { pdf, Document, Page, Text, View } from "@react-pdf/renderer";
import { CourseService } from "~/services/courseService";
import { toaster } from "~/components/ui/toaster";
import { styles } from "./pdfStyles";
import { renderLessonBlocks } from "./pdfUtils";
import { LessonService } from "~/services/lessonService";
import { useConfigStore } from "~/store/configStore";

// --- PDF DOCUMENT COMPONENT ---
const ModuleDocument = ({ module, lessons, courseTitle }: any) => (
  <Document>
    {/* 1. COVER PAGE */}
    <Page size="A4" style={styles.coverPage}>
      <Text
        style={{
          fontSize: 10,
          textTransform: "uppercase",
          letterSpacing: 2,
          marginBottom: 10,
        }}
      >
        COURSE MODULE
      </Text>
      <Text style={styles.moduleTitle}>{module.title}</Text>
      <Text style={{ fontSize: 12, color: "#718096" }}>
        From Course: {courseTitle}
      </Text>

      {/* Table of Contents */}
      <View
        style={{
          marginTop: 50,
          width: "100%",
          padding: 20,
          backgroundColor: "#f7fafc",
          borderRadius: 8,
        }}
      >
        <Text
          style={{ fontSize: 16, fontFamily: "RobotoBold", marginBottom: 15 }}
        >
          Table of Contents
        </Text>
        {lessons.map((l: any, i: number) => (
          <Text key={i} style={styles.tocItem}>
            {i + 1}. {l.title}
          </Text>
        ))}
      </View>
      <Text style={styles.footer}>Generated by CourseForge AI</Text>
    </Page>

    {/* 2. LESSON PAGES */}
    {lessons.map((lesson: any, i: number) => (
      <Page key={lesson._id || i} size="A4" style={styles.page}>
        <View style={{ marginBottom: 20 }}>
          <Text style={styles.subHeader}>Module: {module.title}</Text>
          <Text style={styles.lessonTitle}>
            {i + 1}. {lesson.title}
          </Text>
        </View>

        {/* Render the content blocks */}
        {renderLessonBlocks(lesson.content)}

        <Text style={styles.footer} fixed>
          {module.title} • Lesson {i + 1}
        </Text>
      </Page>
    ))}
  </Document>
);

export const ModulePDFButton = ({
  module,
  courseTitle,
}: {
  module: any;
  courseTitle: string;
}) => {
  const [loading, setLoading] = useState(false);
  const getCost = useConfigStore((state) => state.getCost);
  const cost = getCost("exportModulePdf");
  const handleDownload = async (e: React.MouseEvent) => {
    e.stopPropagation(); // Stop accordion from toggling
    setLoading(true);

    try {
      // 1. 🛑 CHECK IF CONTENT IS MISSING
      // If the first lesson doesn't have a 'content' array, we assume we need to fetch data.
      let fullLessons = module.lessons || [];
      const needsFetch = !fullLessons[0]?.content;

      if (needsFetch) {
        toaster.create({
          description: `Fetching content for ${fullLessons.length} lessons...`,
          type: "info",
        });

        // Fetch all lessons in parallel
        const promises = fullLessons.map((l: any) =>
          LessonService.getLessonById(l._id || l.id),
        );
        fullLessons = await Promise.all(promises);
      }

      // 2. 💳 DEDUCT CREDITS
      await CourseService.deductModulePDFCredits(module._id || module.id);
      toaster.create({ description: "Compiling Module PDF...", type: "info" });

      // 3. 📄 GENERATE PDF
      // We pass 'fullLessons' explicitly to the document
      const doc = (
        <ModuleDocument
          module={module}
          lessons={fullLessons}
          courseTitle={courseTitle}
        />
      );
      const blob = await pdf(doc).toBlob();

      // 4. 💾 SAVE FILE
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      const safeTitle = (module.title || "Module").replace(/\s+/g, "_");
      link.download = `${safeTitle}_Complete.pdf`;
      link.click();
      URL.revokeObjectURL(url);

      toaster.create({ title: "Download Ready", type: "success" });
    } catch (error: any) {
      console.error("PDF Error:", error);
      toaster.create({
        title: "Failed",
        description: error.message,
        type: "error",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button
      size="xs"
      colorPalette="purple"
      variant="ghost"
      onClick={handleDownload}
      loading={loading}
    >
      <FaFilePdf /> PDF (-${cost})
    </Button>
  );
};
